baseURL = "https://pythonbiellagroup.it/"
languageCode = "en-us"
title = "Python Biella Group"
theme = "pythonBG"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir= true
publishDir = "docs"
googleAnalytics = "G-56E78Z4RKM"
enableRobotsTXT = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "blue"
  showVisitedLinks = true
  author = "Andrea Guzzo"
  description = "Python Biella Group Reference Website and Guides"
  version = "v0.2"

[languages]
  [languages.it]
    languageName = "Italiano"
    title = "Benvenuto"
    weight = 1

    [[languages.it.menu.shortcuts]] 
      name = "<i class='fas fa-tags'></i> Tag"
      identifier = "tag"
      url = "/tags"
      weight = 1
    
    [[languages.it.menu.shortcuts]] 
      name = "<i class='fab fa-github'></i> Github"
      identifier = "repo"
      url = "https://github.com/PythonBiellaGroup/"
      weight = 3
    
    [[languages.it.menu.shortcuts]] 
      name = "<i class='fab fa-telegram'></i> Contatti"
      identifier = "telegram"
      url = "https://linktr.ee/PythonBiellaGroup"
      weight = 4

    [[languages.it.menu.shortcuts]] 
      name = "<i class='fab fa-youtube'></i> Youtube"
      identifier = "youtube"
      url = "https://www.youtube.com/c/PythonBiellaGroup"
      weight = 5
  
  [languages.en]
    languageName = "English"
    title = "Python Biella Group"
    weight = 2
  
  [[languages.en.menu.shortcuts]] 
    name = "<i class='fas fa-tags'></i> Tags"
    identifier = "tag"
    url = "/tags"
    weight = 2

  [[languages.en.menu.shortcuts]] 
    name = "<i class='fas fa-tags'></i> Tag"
    identifier = "tag"
    url = "/tags"
    weight = 1
  
  [[languages.en.menu.shortcuts]] 
    name = "<i class='fab fa-github'></i> Github"
    identifier = "repo"
    url = "https://github.com/PythonBiellaGroup/"
    weight = 3
  
  [[languages.en.menu.shortcuts]] 
    name = "<i class='fab fa-telegram'></i> Contacts"
    identifier = "telegram"
    url = "https://linktr.ee/PythonBiellaGroup"
    weight = 4

  [[languages.en.menu.shortcuts]] 
    name = "<i class='fab fa-youtube'></i> Youtube"
    identifier = "youtube"
    url = "https://www.youtube.com/c/PythonBiellaGroup"
    weight = 5